name: Release

on:
  push:
    branches: [release]

jobs:
  eslint:
    name: ESLint
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow/.github/actions/eslint@main

  typecheck:
    name: Typecheck
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow/.github/actions/typecheck@main

  playwrightComponentTesting:
    name: Playwright Component Testing
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow/.github/actions/playwrightComponentTesting@main

  release:
    if: ${{ !contains(github.event.head_commit.message, '~sync') }}
    name: Release
    needs: ['eslint', 'typecheck', 'playwrightComponentTesting']
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow/.github/actions/release@main

  postRelease:
    if: ${{ !contains(github.event.head_commit.message, '~sync') }}
    name: Post release
    needs:
      [
        'eslint',
        'typecheck',
        'playwrightComponentTesting',
        'storybook',
        'release',
      ]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: codingnomad-com/github-workflow/.github/actions/postRelease@main
        with:
          personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN}}
          github_token: ${{ secrets.GITHUB_TOKEN}}
